# Project: DynamicWallpaperTools
# Makefile created by Dev-C++ 5.11

CPP      = g++.exe
CC       = gcc.exe
WINDRES  = windres.exe
RES      = DynamicWallpaperTools_private.res
OBJ      = main.o $(RES)
LINKOBJ  = main.o $(RES)
LIBS     = -L"C:/Users/ywh11/AppData/Local/Programs/Dev-Cpp/MinGW64/lib32" -L"C:/Users/ywh11/AppData/Local/Programs/Dev-Cpp/MinGW64/x86_64-w64-mingw32/lib32" -static-libgcc -O2 -s -flto -mwindows HelpDWPT/libHelpDWPT.a lib32(Used_in_compilation)/liburlmon.a lib32(Used_in_compilation)/libdwmapi.a lib32(Used_in_compilation)/libole32.a lib32(Used_in_compilation)/librpcrt4.a WallpaperCore/libWallpaperCore.a -m32
INCS     = -I"C:/Users/ywh11/AppData/Local/Programs/Dev-Cpp/MinGW64/include" -I"C:/Users/ywh11/AppData/Local/Programs/Dev-Cpp/MinGW64/x86_64-w64-mingw32/include" -I"C:/Users/ywh11/AppData/Local/Programs/Dev-Cpp/MinGW64/lib/gcc/x86_64-w64-mingw32/4.9.2/include"
CXXINCS  = -I"C:/Users/ywh11/AppData/Local/Programs/Dev-Cpp/MinGW64/include" -I"C:/Users/ywh11/AppData/Local/Programs/Dev-Cpp/MinGW64/x86_64-w64-mingw32/include" -I"C:/Users/ywh11/AppData/Local/Programs/Dev-Cpp/MinGW64/lib/gcc/x86_64-w64-mingw32/4.9.2/include" -I"C:/Users/ywh11/AppData/Local/Programs/Dev-Cpp/MinGW64/lib/gcc/x86_64-w64-mingw32/4.9.2/include/c++"
BIN      = DynamicWallpaperTools.exe
CXXFLAGS = $(CXXINCS) -m32 -lgdi32 -lurlmon -luser32
CFLAGS   = $(INCS) -m32 -lgdi32 -lurlmon -luser32
RM       = rm.exe -f

.PHONY: all all-before all-after clean clean-custom

all: all-before $(BIN) all-after

clean: clean-custom
	${RM} $(OBJ) $(BIN)

$(BIN): $(OBJ)
	$(CPP) $(LINKOBJ) -o $(BIN) $(LIBS)

main.o: main.cpp
	$(CPP) -c main.cpp -o main.o $(CXXFLAGS)

DynamicWallpaperTools_private.res: DynamicWallpaperTools_private.rc OtherRes.rc
	$(WINDRES) -i DynamicWallpaperTools_private.rc -F pe-i386 --input-format=rc -o DynamicWallpaperTools_private.res -O coff 

